package com.tju.lab2;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;
//Generated by Selenium IDE
import org.junit.After;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Lab2Test {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		String driverPath = System.getProperty("user.dir") + "/src/chromedriver/chromedriver.exe";
		System.setProperty("webdriver.chrome.driver", driverPath);
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		driver.get("http://103.120.226.190/selenium-demo/git-repo");
		driver.manage().window().setSize(new Dimension(1550, 838));
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void lab2_01() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218053");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/chenkuochih/software_test.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/chenkuochih/software_test.git"));
	}
	
	@Test
	public void lab2_02() {
//		driver.get("http://103.120.226.190/selenium-demo/git-repo");
//		driver.manage().window().setSize(new Dimension(1550, 838));
		driver.findElement(By.name("user_number")).click();
//		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218054");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/roshan0/software_test.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/roshan0/software_test.git"));
	}
	
	@Test
	public void lab2_03() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218055");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/dai88X/software_test.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/dai88X/software_test.git"));
	}
	
	@Test
	public void lab2_04() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218056");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/Bing-Max/SoftwareTest.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/Bing-Max/SoftwareTest.git"));
	}
	
	@Test
	public void lab2_05() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218057");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/YumengGuo/SoftwareTesting");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/YumengGuo/SoftwareTesting"));
	}
	
	@Test
	public void lab2_06() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218058");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/howAreYouHkk/SoftwareTestingTechnology");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/howAreYouHkk/SoftwareTestingTechnology"));
	}
	
	@Test
	public void lab2_07() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218059");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/Eternal144/Software-Testing");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/Eternal144/Software-Testing"));
	}
	
	@Test
	public void lab2_08() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218060");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/HangxueLiu/softwareTest.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/HangxueLiu/softwareTest.git"));
	}
	
	@Test
	public void lab2_09() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218061");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/qq734628996/software-test");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/qq734628996/software-test"));
	}
	
	@Test
	public void lab2_10() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218062");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/cxdzb/software-testing-technology");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/cxdzb/software-testing-technology"));
	}
	
	@Test
	public void lab2_11() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218063");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/PathfinderTJU/Softwate_test_homework");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/PathfinderTJU/Softwate_test_homework"));
	}
	
	@Test
	public void lab2_12() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218064");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/Martin12345677/software_testing_technology");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/Martin12345677/software_testing_technology"));
	}
	
	@Test
	public void lab2_13() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218065");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/panliming0418/softwareTestingTechnology.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/panliming0418/softwareTestingTechnology.git"));
	}
	
	@Test
	public void lab2_14() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218066");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/taytaytaytaylor11/SoftwareTesting");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/taytaytaytaylor11/SoftwareTesting"));
	}
	
	@Test
	public void lab2_15() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218067");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/surumeng/test3017218067");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/surumeng/test3017218067"));
	}
	
	@Test
	public void lab2_16() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218068");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://gitee.com/Sunhanyu/SoftwareTestingTechnology.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://gitee.com/Sunhanyu/SoftwareTestingTechnology.git"));
	}
	
	@Test
	public void lab2_17() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218069");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/HaomingSun-1895/Software-Testing-hw.git");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/HaomingSun-1895/Software-Testing-hw.git"));
	}
	
	@Test
	public void lab2_18() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218070");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/Taoboan1999/Taoboan1999");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/Taoboan1999/Taoboan1999"));
	}
	
	@Test
	public void lab2_19() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218071");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/tianzhaotju/software_testing");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/tianzhaotju/software_testing"));
	}
	
	@Test
	public void lab2_20() {
		driver.findElement(By.name("user_number")).click();
		driver.findElement(By.name("user_number")).sendKeys("3017218072");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("https://github.com/ZhaomengWang/software_testing");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".p-5")).click();
		assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(),
				is("https://github.com/ZhaomengWang/software_testing"));
	}
}
